### ISSUE TITLE
Consider removing optimization for huge patches

### ISSUE THREAD

**Issue by tomalec** [Palindrom/palindrom-client#80] opened 2018-09-19 13:15 UTC
@alshakero suggested to remove it at https://github.com/Palindrom/palindrom-client/pull/79#discussion_r218492059, as

> We agreed that it's too hacky and didn't help Palma.

**Comment by alshakero** [comment] 2018-11-15 15:11
Closing as done in https://github.com/Palindrom/palindrom-client/commit/2408b985564e9bbb5d1ef5ebf1b4cce16269c083

**Closed by alshakero** 2018-11-15 15:11 UTC
Labels: enhancement

**Comment by warpech** [comment] 2019-09-02 12:03
The reason the threshold was added in PR https://github.com/Palindrom/palindrom-client/pull/73 is that I thought that it was a clever hack to address a performance problem caused by massive mutations.

The reason why the said feature was removed in this PR (https://github.com/Palindrom/palindrom-client/pull/80) is that I quickly came to conclusion that not only it did not fully fix the original problem, but it also affected the UX in a negative way. Replacing the whole state object causes the whole DOM tree to be re-rendered, losing any focus in input fields, showing flash of unstyled content, etc). To add injury to the insult, the threshold feature would ultimately cover any underlying problem instead of fixing it. Arguably, the best way to fix a problem with too many notifications is to change the architecture or patch collection mechanism to reduce the number of notifications.
